// KYWARD - THEME & STYLES SYSTEM

export const styles = {
  landingContainer: { backgroundColor: '#000', color: '#E5E5E5', minHeight: '100vh', fontFamily: '"Space Grotesk", sans-serif' },
  nav: { position: 'fixed', top: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.95)', backdropFilter: 'blur(10px)', borderBottom: '1px solid #1a1a1a', zIndex: 1000, padding: '16px 0' },
  navContent: { maxWidth: '1200px', margin: '0 auto', padding: '0 24px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  navLogo: { display: 'flex', alignItems: 'center', gap: '12px' },
  navLogoText: { fontSize: '24px', fontWeight: '700', color: '#F7931A' },
  navButtons: { display: 'flex', gap: '12px' },
  navButtonLogin: { padding: '10px 20px', backgroundColor: 'transparent', border: '1px solid #3a3a3a', color: '#E5E5E5', borderRadius: '8px', fontSize: '14px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.3s' },
  navButtonSignup: { padding: '10px 24px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '8px', fontSize: '14px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.3s' },
  hero: { paddingTop: '140px', paddingBottom: '100px', minHeight: '90vh', display: 'flex', alignItems: 'center', position: 'relative' },
  heroBackground: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, overflow: 'hidden' },
  orangeGlow: { position: 'absolute', width: '500px', height: '500px', borderRadius: '50%', background: 'radial-gradient(circle, rgba(247,147,26,0.15) 0%, transparent 70%)', animation: 'pulse 4s ease-in-out infinite' },
  heroContent: { maxWidth: '600px', margin: '0 auto', padding: '0 24px', position: 'relative', zIndex: 1 },
  heroBadge: { display: 'inline-block', padding: '8px 16px', backgroundColor: 'rgba(247,147,26,0.1)', border: '1px solid #F7931A', borderRadius: '20px', fontSize: '12px', fontWeight: '700', color: '#F7931A', marginBottom: '24px' },
  heroTitle: { fontSize: '72px', fontWeight: '800', color: '#fff', lineHeight: '1.1', marginBottom: '24px', letterSpacing: '-2px' },
  heroTitleAccent: { color: '#F7931A' },
  heroSubtitle: { fontSize: '20px', color: '#9ca3af', lineHeight: '1.6', marginBottom: '40px' },
  heroButtons: { display: 'flex', gap: '16px', marginBottom: '60px' },
  heroCTA: { padding: '18px 36px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '12px', fontSize: '18px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.3s', display: 'flex', alignItems: 'center', gap: '12px' },
  heroCtaArrow: { fontSize: '20px' },
  heroSecondary: { padding: '18px 36px', backgroundColor: 'transparent', border: '2px solid #3a3a3a', color: '#E5E5E5', borderRadius: '12px', fontSize: '18px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.3s' },
  heroStats: { display: 'flex', gap: '40px', alignItems: 'center' },
  heroStat: { textAlign: 'center' },
  heroStatNumber: { fontSize: '36px', fontWeight: '800', color: '#F7931A', marginBottom: '4px' },
  heroStatLabel: { fontSize: '13px', color: '#6b7280', fontWeight: '600', textTransform: 'uppercase' },
  heroStatDivider: { width: '1px', height: '40px', backgroundColor: '#2a2a2a' },
  heroImage: { position: 'absolute', right: '80px', top: '50%', transform: 'translateY(-50%)', zIndex: 2 },
  mockupCard: { width: '380px', backgroundColor: '#1a1a1a', borderRadius: '16px', border: '1px solid #2a2a2a', overflow: 'hidden', boxShadow: '0 20px 60px rgba(247,147,26,0.2)' },
  mockupHeader: { padding: '16px', borderBottom: '1px solid #2a2a2a' },
  mockupDots: { display: 'flex', gap: '8px' },
  mockupDot: { width: '12px', height: '12px', borderRadius: '50%' },
  mockupContent: { padding: '32px' },
  mockupTitle: { fontSize: '14px', color: '#6b7280', marginBottom: '24px', textTransform: 'uppercase', fontWeight: '600' },
  mockupScoreContainer: { position: 'relative', width: '120px', height: '120px', margin: '0 auto 32px' },
  mockupScore: { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%,-50%)', fontSize: '42px', fontWeight: '800', color: '#F7931A' },
  mockupRecommendations: { display: 'flex', flexDirection: 'column', gap: '12px' },
  mockupRecItem: { display: 'flex', alignItems: 'center', gap: '12px', fontSize: '13px', color: '#9ca3af' },
  mockupRecIcon: { width: '24px', height: '24px', borderRadius: '6px', backgroundColor: '#22c55e', color: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: '700' },
  pvuSection: { padding: '120px 0', backgroundColor: '#0a0a0a' },
  sectionContent: { maxWidth: '1200px', margin: '0 auto', padding: '0 24px' },
  sectionTitle: { fontSize: '48px', fontWeight: '800', color: '#fff', textAlign: 'center', marginBottom: '16px' },
  sectionSubtitle: { fontSize: '18px', color: '#6b7280', textAlign: 'center', maxWidth: '600px', margin: '0 auto 60px' },
  pvuGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '24px' },
  pvuCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '32px', transition: 'all 0.3s' },
  pvuIcon: { fontSize: '48px', marginBottom: '20px' },
  pvuTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '12px' },
  pvuText: { fontSize: '16px', color: '#9ca3af', lineHeight: '1.6' },
  howSection: { padding: '120px 0', backgroundColor: '#000' },
  stepsContainer: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '32px' },
  stepCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '32px', animation: 'fadeInUp 0.6s' },
  stepNumber: { fontSize: '14px', fontWeight: '800', color: '#F7931A', marginBottom: '16px' },
  stepTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '12px' },
  stepText: { fontSize: '15px', color: '#9ca3af', lineHeight: '1.6', marginBottom: '24px' },
  stepImage: { width: '100%', height: '160px' },
  stepImagePlaceholder: { width: '100%', height: '100%', backgroundColor: '#0a0a0a', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  stepImageIcon: { fontSize: '48px' },
  benefitsSection: { padding: '120px 0', backgroundColor: '#0a0a0a' },
  benefitsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '80px', alignItems: 'center' },
  benefitsLeft: {},
  benefitsTitle: { fontSize: '52px', fontWeight: '800', color: '#fff', marginBottom: '24px', lineHeight: '1.1' },
  benefitsText: { fontSize: '18px', color: '#9ca3af', lineHeight: '1.6', marginBottom: '32px' },
  benefitsCTA: { padding: '16px 32px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer' },
  benefitsRight: { display: 'flex', flexDirection: 'column', gap: '24px' },
  benefitItem: { display: 'flex', gap: '20px', alignItems: 'flex-start', padding: '24px', backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '12px' },
  benefitIcon: { fontSize: '32px' },
  benefitItemTitle: { fontSize: '18px', fontWeight: '700', color: '#fff', marginBottom: '6px' },
  benefitItemText: { fontSize: '14px', color: '#9ca3af' },
  pricingSection: { padding: '120px 0', backgroundColor: '#000' },
  pricingGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '32px', maxWidth: '900px', margin: '0 auto' },
  pricingCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '40px' },
  pricingCardFeatured: { border: '2px solid #F7931A', transform: 'scale(1.05)' },
  pricingBadge: { display: 'inline-block', padding: '6px 12px', backgroundColor: '#2a2a2a', color: '#9ca3af', borderRadius: '6px', fontSize: '11px', fontWeight: '700', marginBottom: '20px' },
  pricingTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '16px' },
  pricingPrice: { fontSize: '48px', fontWeight: '800', color: '#F7931A', marginBottom: '32px' },
  pricingPeriod: { fontSize: '18px', fontWeight: '600', color: '#6b7280' },
  pricingFeatures: { listStyle: 'none', padding: 0, margin: '0 0 32px 0' },
  pricingFeature: { fontSize: '15px', color: '#9ca3af', marginBottom: '12px' },
  pricingButton: { width: '100%', padding: '16px', backgroundColor: 'transparent', border: '2px solid #3a3a3a', color: '#E5E5E5', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer' },
  pricingButtonFeatured: { width: '100%', padding: '16px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer' },
  footerCTA: { padding: '100px 24px', textAlign: 'center', backgroundColor: '#0a0a0a' },
  footerCTATitle: { fontSize: '48px', fontWeight: '800', color: '#fff', marginBottom: '16px' },
  footerCTAText: { fontSize: '20px', color: '#6b7280', marginBottom: '40px' },
  footerCTAButton: { padding: '18px 48px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '12px', fontSize: '18px', fontWeight: '700', cursor: 'pointer' },
  footer: { padding: '40px 24px', backgroundColor: '#000', borderTop: '1px solid #1a1a1a' },
  footerContent: { maxWidth: '1200px', margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  footerLeft: {},
  footerLogo: { display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '12px' },
  footerLogoText: { fontSize: '20px', fontWeight: '700', color: '#F7931A' },
  footerTagline: { fontSize: '14px', color: '#6b7280' },
  footerRight: {},
  footerCopyright: { fontSize: '14px', color: '#6b7280' },
  authContainer: { minHeight: '100vh', backgroundColor: '#000', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '40px 20px', fontFamily: '"Space Grotesk", sans-serif' },
  authCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '48px', maxWidth: '500px', width: '100%', position: 'relative' },
  backButton: { position: 'absolute', top: '20px', left: '20px', padding: '8px 16px', backgroundColor: 'transparent', border: '1px solid #2a2a2a', color: '#9ca3af', borderRadius: '8px', fontSize: '14px', cursor: 'pointer' },
  authLogo: { textAlign: 'center', marginBottom: '32px', marginTop: '20px' },
  authTitle: { fontSize: '32px', fontWeight: '800', color: '#F7931A', marginTop: '16px', marginBottom: '8px' },
  authSubtitle: { fontSize: '16px', color: '#9ca3af' },
  successBox: { backgroundColor: 'rgba(34,197,94,0.1)', border: '1px solid #22c55e', color: '#22c55e', padding: '16px', borderRadius: '10px', marginBottom: '24px', fontSize: '15px', fontWeight: '600', textAlign: 'center' },
  errorBox: { backgroundColor: 'rgba(239,68,68,0.1)', border: '1px solid #ef4444', color: '#ef4444', padding: '16px', borderRadius: '10px', marginBottom: '24px', fontSize: '15px', fontWeight: '600', textAlign: 'center' },
  inputGroup: { marginBottom: '20px' },
  label: { display: 'block', fontSize: '14px', fontWeight: '600', color: '#E5E5E5', marginBottom: '8px' },
  input: { width: '100%', padding: '14px 16px', backgroundColor: '#0a0a0a', border: '1px solid #2a2a2a', color: '#E5E5E5', borderRadius: '10px', fontSize: '15px', boxSizing: 'border-box' },
  passwordReqs: { backgroundColor: '#0a0a0a', border: '1px solid #2a2a2a', borderRadius: '10px', padding: '16px', marginBottom: '24px' },
  reqItem: { fontSize: '13px', color: '#9ca3af', marginBottom: '8px', display: 'flex', alignItems: 'center', gap: '8px' },
  authSubmit: { width: '100%', padding: '16px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px' },
  spinner: { width: '16px', height: '16px', border: '2px solid rgba(0,0,0,0.3)', borderTop: '2px solid #000', borderRadius: '50%', animation: 'spin 0.8s linear infinite' },
  authFooter: { textAlign: 'center', marginTop: '24px', fontSize: '14px', color: '#6b7280' },
  authLink: { color: '#F7931A', fontWeight: '600', cursor: 'pointer', textDecoration: 'underline' },
  dashContainer: { minHeight: '100vh', backgroundColor: '#000', fontFamily: '"Space Grotesk", sans-serif' },
  dashNav: { backgroundColor: '#0a0a0a', borderBottom: '1px solid #1a1a1a', padding: '16px 0' },
  logoutBtn: { padding: '10px 20px', backgroundColor: 'transparent', border: '1px solid #2a2a2a', color: '#9ca3af', borderRadius: '8px', fontSize: '14px', fontWeight: '600', cursor: 'pointer' },
  dashContent: { maxWidth: '1000px', margin: '0 auto', padding: '60px 24px', textAlign: 'center' },
  dashTitle: { fontSize: '42px', fontWeight: '800', color: '#fff', marginBottom: '12px' },
  dashSubtitle: { fontSize: '16px', color: '#6b7280', marginBottom: '20px' },
  dashBadge: { display: 'inline-block', padding: '10px 20px', backgroundColor: 'rgba(247,147,26,0.1)', border: '1px solid #F7931A', borderRadius: '20px', fontSize: '14px', fontWeight: '700', color: '#F7931A', marginBottom: '40px' },
  dashStats: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '24px', marginBottom: '40px' },
  statCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '12px', padding: '32px', textAlign: 'center' },
  statIcon: { fontSize: '36px', marginBottom: '16px' },
  statNum: { fontSize: '40px', fontWeight: '800', color: '#F7931A', marginBottom: '8px' },
  statLabel: { fontSize: '14px', color: '#6b7280', fontWeight: '600' },
  infoBox: { backgroundColor: '#1a1a1a', border: '1px solid #22c55e', borderRadius: '12px', padding: '32px', textAlign: 'left' },
  infoTitle: { fontSize: '22px', fontWeight: '700', color: '#22c55e', marginBottom: '16px' },
  infoText: { fontSize: '15px', color: '#E5E5E5', lineHeight: '1.6', marginBottom: '12px' },
  ctaCard: { backgroundColor: '#1a1a1a', border: '2px solid #F7931A', borderRadius: '16px', padding: '40px', marginBottom: '32px', textAlign: 'center' },
  ctaTitle: { fontSize: '28px', fontWeight: '800', color: '#fff', marginBottom: '12px' },
  ctaText: { fontSize: '16px', color: '#9ca3af', marginBottom: '24px' },
  startButton: { padding: '16px 48px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '12px', fontSize: '18px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.3s' },
  upgradeText: { fontSize: '14px', color: '#9ca3af', marginTop: '16px' },
  questionnaireContainer: { maxWidth: '800px', margin: '0 auto', padding: '40px 24px' },
  progressBar: { width: '100%', height: '8px', backgroundColor: '#2a2a2a', borderRadius: '4px', overflow: 'hidden', marginBottom: '12px' },
  progressFill: { height: '100%', backgroundColor: '#F7931A', transition: 'width 0.3s ease' },
  progressText: { fontSize: '14px', color: '#9ca3af', marginBottom: '32px', textAlign: 'center' },
  questionCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '40px' },
  questionTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '32px', lineHeight: '1.4' },
  optionsContainer: { display: 'flex', flexDirection: 'column', gap: '16px', marginBottom: '32px' },
  optionItem: { backgroundColor: '#0a0a0a', border: '2px solid #2a2a2a', borderRadius: '12px', padding: '16px', transition: 'all 0.3s', cursor: 'pointer' },
  optionLabel: { display: 'flex', alignItems: 'center', gap: '12px', cursor: 'pointer', width: '100%' },
  optionInput: { width: '20px', height: '20px', cursor: 'pointer', accentColor: '#F7931A' },
  optionText: { fontSize: '16px', color: '#E5E5E5', flex: 1 },
  questionButtons: { display: 'flex', gap: '16px', justifyContent: 'space-between' },
  prevButton: { padding: '14px 32px', backgroundColor: 'transparent', border: '2px solid #2a2a2a', color: '#E5E5E5', borderRadius: '10px', fontSize: '16px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.3s' },
  nextButton: { padding: '14px 32px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.3s' },
  submitButton: { padding: '14px 48px', backgroundColor: '#22c55e', border: 'none', color: '#000', borderRadius: '10px', fontSize: '16px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.3s' },
  reportContainer: { maxWidth: '900px', margin: '0 auto', padding: '60px 24px' },
  reportCard: { backgroundColor: '#1a1a1a', border: '1px solid #2a2a2a', borderRadius: '16px', padding: '48px', textAlign: 'center' },
  reportTitle: { fontSize: '36px', fontWeight: '800', color: '#fff', marginBottom: '40px' },
  scoreCircle: { position: 'relative', width: '200px', height: '200px', margin: '0 auto 24px' },
  scoreNumber: { position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', fontSize: '64px', fontWeight: '800', color: '#F7931A' },
  scoreLabel: { fontSize: '24px', fontWeight: '700', marginBottom: '48px' },
  recsSection: { textAlign: 'left', marginBottom: '48px' },
  recsTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '24px' },
  recItem: { backgroundColor: '#0a0a0a', padding: '16px', borderRadius: '10px', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '16px' },
  recIcon: { fontSize: '24px' },
  recText: { fontSize: '16px', color: '#E5E5E5', flex: 1 },
  planSection: { textAlign: 'left', marginBottom: '48px' },
  planTitle: { fontSize: '24px', fontWeight: '700', color: '#fff', marginBottom: '24px' },
  planCategory: { marginBottom: '24px' },
  planCategoryTitle: { fontSize: '18px', fontWeight: '700', color: '#F7931A', marginBottom: '12px' },
  planItem: { fontSize: '15px', color: '#E5E5E5', marginBottom: '8px', paddingLeft: '8px' },
  reportButton: { padding: '16px 48px', backgroundColor: '#F7931A', border: 'none', color: '#000', borderRadius: '12px', fontSize: '18px', fontWeight: '700', cursor: 'pointer', transition: 'all 0.3s' },
};

// Lógica de inyección de estilos globales (Fonts y Animaciones)
if (typeof document !== 'undefined') {
  const styleSheet = document.createElement("style");
  styleSheet.textContent = `
    @import url('https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700;800&display=swap');
    @keyframes pulse { 0%, 100% { opacity: 0.15; transform: scale(1); } 50% { opacity: 0.25; transform: scale(1.05); } }
    @keyframes fadeInUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
    @keyframes spin { to { transform: rotate(360deg); } }
    button:hover:not(:disabled) { transform: translateY(-2px); }
    input:focus { outline: none; border-color: #F7931A !important; }
  `;
  document.head.appendChild(styleSheet);
}